version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: ex_aws
    versions:
    - 2.1.7
    - 2.1.8
    - 2.1.9
    - 2.2.0
  - dependency-name: timex
    versions:
    - 3.6.3
    - 3.6.4
    - 3.7.1
    - 3.7.3
  - dependency-name: scrivener
    versions:
    - 2.7.1
  - dependency-name: hackney
    versions:
    - 1.17.0
    - 1.17.1
    - 1.17.2
    - 1.17.3
  - dependency-name: floki
    versions:
    - 0.30.0
  - dependency-name: phoenix_live_reload
    versions:
    - 1.3.0
- package-ecosystem: npm
  directory: "/assets"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
