scss_files: "**/*.scss"

severity: warning

linters:
  IdSelector:
    enabled: false

  SelectorDepth:
    enabled: true
    max_depth: 5

  ColorVariable:
    enabled: false

  NestingDepth:
    max_depth: 5

  QualifyingElement:
    enabled: false

  StringQuotes:
    enabled: true
    style: double_quotes

