version: '2'
services:
  storage:
    image: busybox
    volumes:
      - /var/lib/mysql
  mysql:
    image: mysql:5.7
    volumes_from:
      - storage
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"

  elixir:
    image: h3poteto/elixir-node:1.9.1-node10-slim-stretch
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      GOOGLE_CUSTOM_SEARCH_ID: $GOOGLE_CUSTOM_SEARCH_ID
      GOOGLE_API_KEY: $GOOGLE_API_KEY
      SLACK_WEBHOOK_URL: $SLACK_WEBHOOK_URL
      AWS_S3_BUCKET: seiyu-watch-dev
      DB_HOST: postgres
      DB_USER: postgres
    volumes:
      - .:/var/opt/app
    links:
      - mysql:mysql
      - postgres:postgres
    ports:
      - "4000:4000"
    command: /bin/bash

  postgres:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: seiyu_watch_dev
    volumes:
      - storage:/var/lib/postgres/data
    ports:
      - "5432:5432"

volumes:
  storage:
