version: '2'
services:
  elixir:
    image: ghcr.io/h3poteto/elixir-node:1.14.5-node18-slim
    user: root
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      GOOGLE_CUSTOM_SEARCH_ID: $GOOGLE_CUSTOM_SEARCH_ID
      GOOGLE_API_KEY: $GOOGLE_API_KEY
      SLACK_WEBHOOK_URL: $SLACK_WEBHOOK_URL
      AWS_S3_BUCKET: seiyu-watch-dev
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: password
    volumes:
      - .:/var/opt/app
      - deps:/var/opt/app/deps
      - build:/var/opt/app/_build
      - node_modules:/var/opt/app/assets/node_modules
    links:
      - postgres:postgres
    ports:
      - "4000:4000"
    command: /bin/bash

  postgres:
    image: postgres:13.12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: seiyu_watch_dev
    volumes:
      - storage:/var/lib/postgres/data
    ports:
      - "5432:5432"

volumes:
  storage:
  deps:
  build:
  node_modules:
