version: 2
jobs:
  build:
    docker:
      - image: h3poteto/phoenix:1.5.1
        environment:
          DB_HOST: 127.0.0.1
          # MySQLの起動チェック用
          HEALTH_CHECK_RETRY_LIMIT: 10
          HEALTH_CHECK_RETRY_WAIT: 3
      - image: mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes

    working_directory: /var/opt/app
    steps:
      - checkout
      - run:
          name: Check elixir version
          command: elixir --version
      - run:
          name: Check node version
          command: node --version
      - restore_cache:
          name: Restoring cache - deps
          keys:
            - vendor-{{ checksum "mix.exs" }}-{{ checksum "mix.lock" }}
            - vendor-{{ checksum "mix.exs" }}-
      - restore_cache:
          name: Restoring cache - _build
          keys:
            - _build-{{ checksum "mix.exs" }}-{{ checksum "mix.lock" }}
            - _build-{{ checksum "mix.exs" }}
      - restore_cache:
          name: Restoring cache - node_modules
          keys:
            - node_modules-{{ checksum "assets/package-lock.json" }}
            - node_modules-
      - run:
          name: Mix packages install
          command: mix deps.get
      - save_cache:
          name: Saving cache - deps
          key: deps-{{ checksum "mix.exs" }}-{{ checksum "mix.lock" }}
          paths:
            - "deps"
      - run:
          name: Compile deps packages
          command: |
            mix local.hex --force
            mix local.rebar --force
            mix deps.compile
      - save_cache:
          name: Saving cache - _build
          key: _build-{{ checksum "mix.exs" }}-{{ checksum "mix.lock" }}
          paths:
            - "_build"
      - run:
          name: Node packages install
          command: |
            cd assets && npm install
      - save_cache:
          name: Saving cache - node_modules
          key: node_modules-{{ checksum "assets/package-lock.json" }}
          paths:
            - "assets/node_modules"
      - run:
          name: Checking mysql connection
          command: |
            for i in $(seq $HEALTH_CHECK_RETRY_LIMIT)
            do
              mysql -u root -h 127.0.0.1 -e 'show databases' || (sleep $HEALTH_CHECK_RETRY_WAIT; false) && break
            done
      - run:
          name: Migration database
          command: |
            mix ecto.create
            mix ecto.migrate
      - run:
          name: test
          command: mix test

  deploy:
    docker:
      - image: h3poteto/phoenix
        user: root
        environment:
          AWS_ECR_REPOSITORY: 564677439943.dkr.ecr.ap-northeast-1.amazonaws.com/h3poteto/seiyu_watch
    working_directory: /var/opt/app
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.09.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Install aws command
          command: |
            apt-get update && apt-get install -y python-pip
            pip install awscli
      - run:
          name: Build and push
          command: |
            $(aws ecr get-login --no-include-email --region ap-northeast-1)
            docker build -t $AWS_ECR_REPOSITORY:latest .
            docker push $AWS_ECR_REPOSITORY:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - build

