version: 2
jobs:
  build:
    docker:
      - image: h3poteto/phoenix:1.5.1
        environment:
          DB_HOST: 127.0.0.1
          # MySQLの起動チェック用
          HEALTH_CHECK_RETRY_LIMIT: 10
          HEALTH_CHECK_RETRY_WAIT: 3
      - image: mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes

    working_directory: /var/opt/app
    steps:
      - checkout
      - run:
          name: Check elixir version
          command: elixir --version
      - run:
          name: Check node version
          command: node --version
      - restore_cache:
          name: Restoring cache - deps
          keys:
            - vendor-{{ checksum "mix.exs" }}-{{ checksum "mix.lock" }}
            - vendor-{{ checksum "mix.exs" }}-
      - restore_cache:
          name: Restoring cache - _build
          keys:
            - _build-{{ checksum "mix.exs" }}-{{ checksum "mix.lock" }}
            - _build-{{ checksum "mix.exs" }}
      - restore_cache:
          name: Restoring cache - node_modules
          keys:
            - node_modules-{{ checksum "assets/package-lock.json" }}
            - node_modules-
      - run:
          name: Mix packages install
          command: mix deps.get
      - save_cache:
          name: Saving cache - deps
          key: deps-{{ checksum "mix.exs" }}-{{ checksum "mix.lock" }}
          paths:
            - "deps"
      - run:
          name: Compile deps packages
          command: |
            mix local.hex --force
            mix local.rebar --force
            mix deps.compile
      - save_cache:
          name: Saving cache - _build
          key: _build-{{ checksum "mix.exs" }}-{{ checksum "mix.lock" }}
          paths:
            - "_build"
      - run:
          name: Node packages install
          command: |
            cd assets && npm install
      - save_cache:
          name: Saving cache - node_modules
          key: node_modules-{{ checksum "assets/package-lock.json" }}
          paths:
            - "assets/node_modules"
      - run:
          name: Checking mysql connection
          command: |
            for i in $(seq $HEALTH_CHECK_RETRY_LIMIT)
            do
              mysql -u root -h 127.0.0.1 -e 'show databases' || (sleep $HEALTH_CHECK_RETRY_WAIT; false) && break
            done
      - run:
          name: Migration database
          command: |
            mix ecto.create
            mix ecto.migrate
      - run:
          name: test
          command: mix test

  image:
    machine: true
    steps:
      - checkout
      - run:
          name: Check docker version
          command: docker version
      - run:
          name: Docker build
          command: docker build -t $AWS_ECR_REPOSITORY:$CIRCLE_SHA1 .
      - run:
          name: Docker push
          command: |
            $(aws ecr get-login --no-include-email --region ap-northeast-1)
            docker push $AWS_ECR_REPOSITORY:$CIRCLE_SHA1
  deploy:
    machine: true
    environment:
      - CLUSTER_NAME: base-default-prd
      - SERVICE_NAME: seiyuwatch-web-prd
      - AWS_DEFAULT_REGION: ap-northeast-1
      - RUN_TASK_DEFINITION: seiyuwatch-web-prd-task:1
    steps:
      - checkout
      - run: &prepare_goploy
          name: Preparing ecs-goploy
          command: |
            wget https://github.com/h3poteto/ecs-goploy/releases/download/v0.3.6/ecs-goploy_v0.3.6_linux_amd64.zip
            unzip ecs-goploy_v0.3.6_linux_amd64.zip
            ./ecs-goploy version
      - run: &migrate
          name: migrate
          command: |
             ./ecs-goploy task --cluster ${CLUSTER_NAME} --container-name task --image $AWS_ECR_REPOSITORY:$CIRCLE_SHA1 --timeout 600 --task-definition ${RUN_TASK_DEFINITION} --command "mix ecto.migrate"
      - run: &deploy
          name: ecs deploy
          command: |
            $(aws ecr get-login --no-include-email --region ap-northeast-1)
            ./ecs-goploy service --cluster ${CLUSTER_NAME} --service-name ${SERVICE_NAME} --image $AWS_ECR_REPOSITORY:$CIRCLE_SHA1 --timeout 600 --enable-rollback --skip-check-deployments

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - image:
          filters:
            branches:
              only:
                - master
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - image
            - build

