version: '3'
services:
  phoenix:
    image: h3poteto/seiyu_watch
    environment:
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      SECRET_KEY_BASE: $SECRET_KEY_BASE
      GOOGLE_API_KEY: $GOOGLE_API_KEY
      GOOGLE_CUSTOM_SEARCH_ID: $GOOGLE_CUSTOM_SEARCH_ID
      SLACK_WEBHOOK_URL: $SLACK_WEBHOOK_URL
      RELX_REPLACE_OS_VARS: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8080"]
      interval: 20s
      timeout: 10s
      retries: 3
    deploy:
      replicas: 2
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
        window: 120s
      update_config:
        parallelism: 1
        delay: 20s
    stop_grace_period: 20s
  nginx:
    image: nginx:stable-alipne
    depends_on:
      - phoenix
    ports:
      - "80:80"
      - "443:443"
    environment:
      SERVER_ADDR: phoenix
      SERVER_PORT: 4000
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf.template:ro
      - /var/log/nginx/:/var/log/nginx/
    command: /bin/sh -c "envsubst '$$SERVER_ADDR$$SERVER_PORT' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 20s
      timeout: 10s
      retries: 3
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 20s
    stop_grace_period: 10s
