name: Build

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_HOST: 127.0.0.1
      DB_USER: postgres
      DB_PASSWORD: password
      MIX_ENV: test

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: seiyu_watch_test
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@master
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0"
          elixir-version: "1.17.2"
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Mix install
        run: |
          mix local.hex --force
          mix deps.get
      - name: NPM install
        working-directory: assets
        run: |
          npm install
          npm run compile
      - name: Compile
        run: |
          mix local.rebar --force
          mix deps.compile
          mix compile
      - name: Migration
        run: |
          mix ecto.create
          mix ecto.migrate
      - name: Test
        run: |
          mix test
